import { Component } from '@angular/core';

function log(target: any, name: any, descriptor: any) {
  // console.log(target, name, descriptor)
  // store the original function in a variable
  const original = descriptor.value

  // do some stuff with the descritor.value
  descriptor.value = function(args: any) {
    console.log("Arguments ", args, " we were passed this function")
    const result = original.call(this, args)
    console.log("The result of the functions is ", result)
    return result
  }

  // return the descriptor
  return descriptor
}


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro';

  constructor() {
    console.log("This statement was generated by the constructor: ", this.SimpleMethod(5))
  }

  @log
  SimpleMethod(a:any) {
    return a*a
  }
}
